<?php
declare(strict_types=1);

namespace T3SBS\T3sbootstrapBuilder\Service;

use T3SBS\T3sbootstrapBuilder\Definition\BootstrapVariableRegistry;

/**
 * Serializes the variable key/value map into the SCSS that t3sbootstrap stores
 * in tx_t3sbootstrap_domain_model_config.custom_variables_scss.
 *
 * Output mirrors Bootstrap's expectation: variables defined with !default BEFORE
 * the bootstrap import. t3sbootstrap places custom-variables-{uid}.scss exactly there.
 */
final class ScssVariableService
{
    public function __construct(
        private readonly BootstrapVariableRegistry $registry,
    ) {}

    /**
     * @param array<string, string> $values key => raw scss value (only overrides differing from default)
     * @param array<int, string> $definedVars variable names (without $) known to be defined
     *        earlier in the compiled file (e.g. from the chosen Bootswatch preset). Values
     *        referencing a $var NOT in this set are dropped to avoid "undefined variable" errors.
     * @param array<int, string> $warnings collects human-readable notes about dropped values (by-ref)
     */
    public function buildVariablesScss(array $values, array $definedVars = [], array &$warnings = []): string
    {
        $flat = $this->registry->getFlat();
        $defined = array_flip($definedVars);
        $lines = ['// Generated by EXT:t3sbootstrap_builder – do not edit manually', ''];
        foreach ($values as $key => $value) {
            if (!isset($flat[$key]) || $value === '' || $value === null) {
                continue;
            }
            // Detect $variable references in the value.
            if (preg_match_all('/\$([a-z0-9-]+)/i', (string)$value, $m)) {
                $unresolved = [];
                foreach ($m[1] as $ref) {
                    if (!isset($defined[$ref])) {
                        $unresolved[] = '$' . $ref;
                    }
                }
                if ($unresolved !== []) {
                    $warnings[] = sprintf(
                        '$%s references %s which is not defined (no matching preset). Value ignored.',
                        $key,
                        implode(', ', $unresolved)
                    );
                    continue;
                }
            }
            $lines[] = sprintf('$%s: %s;', $key, $this->normalize($flat[$key]['type'], $value));
        }
        return implode("\n", $lines) . "\n";
    }

    /**
     * Extracts the variable names a preset's _variables.scss defines, so the editor can
     * validate user references against them.
     *
     * @return array<int, string>
     */
    public function extractDefinedVariables(string $presetVariablesScss): array
    {
        if (preg_match_all('/^\s*\$([a-z0-9-]+)\s*:/im', $presetVariablesScss, $m)) {
            return array_values(array_unique($m[1]));
        }
        return [];
    }

    /**
     * Resolves a preset's _variables.scss into concrete values for the registry fields,
     * so the editor can be pre-filled when a preset is chosen.
     *
     * Parses all "$name: value !default;" lines, then resolves simple $variable references
     * (e.g. $primary: $blue) against the same map. Only keys present in the registry are
     * returned. Values that stay unresolved (functions/maps) are skipped.
     *
     * @return array<string, string> registry key => resolved literal value
     */
    public function resolvePresetValues(string $presetVariablesScss): array
    {
        // 1. Collect raw declarations.
        $raw = [];
        if (preg_match_all('/^\s*\$([a-z0-9-]+)\s*:\s*(.+?)\s*(?:!default)?\s*;/im', $presetVariablesScss, $m, PREG_SET_ORDER)) {
            foreach ($m as $row) {
                $raw[$row[1]] = trim($row[2]);
            }
        }

        // 2. Resolve simple $var references (one level deep, iteratively).
        $resolve = static function (string $value) use (&$raw, &$resolve, &$depth): string {
            $depth = ($depth ?? 0);
            if ($depth > 10) {
                return $value;
            }
            if (preg_match('/^\$([a-z0-9-]+)$/i', $value, $mm) && isset($raw[$mm[1]])) {
                $depth++;
                $r = $resolve($raw[$mm[1]]);
                $depth--;
                return $r;
            }
            return $value;
        };

        // 3. Keep only registry keys with a literal (non-$, non-function) result.
        $flat = $this->registry->getFlat();
        $out = [];
        foreach ($raw as $name => $value) {
            if (!isset($flat[$name])) {
                continue;
            }
            $resolved = $resolve($value);
            // Skip values that still reference a variable or use SCSS functions.
            if (str_contains($resolved, '$') || preg_match('/[a-z-]+\s*\(/i', $resolved)) {
                continue;
            }
            $out[$name] = $resolved;
        }
        return $out;
    }

    /**
     * Filters a posted value map down to non-empty overrides only.
     *
     * @param array<string, string> $posted
     * @return array<string, string>
     */
    public function filterOverrides(array $posted): array
    {
        $flat = $this->registry->getFlat();
        $out = [];
        foreach ($flat as $key => $def) {
            $val = trim((string)($posted[$key] ?? ''));
            if ($val !== '' && $val !== (string)$def['default']) {
                $out[$key] = $val;
            }
        }
        return $out;
    }

    /**
     * @return array<string, string> key => default value, for every registered variable.
     */
    public function getFlatDefaults(): array
    {
        $out = [];
        foreach ($this->registry->getFlat() as $key => $def) {
            $out[$key] = (string)$def['default'];
        }
        return $out;
    }

    /**
     * Build a COMPLETE pre-bootstrap variables file from all builder values (single source
     * of truth). Every known variable gets one line; the file fully replaces the previous
     * content. No !default flags, so these values win over Bootstrap's own defaults.
     *
     * @param array<string, string> $values key => value (already merged: defaults + overrides)
     */
    public function buildCompleteVariablesScss(array $values): string
    {
        $flat = $this->registry->getFlat();
        $lines = [
            '// Generated by EXT:t3sbootstrap_builder - single source of truth.',
            '// This file is fully overwritten on each Apply. Do not edit manually.',
            '',
        ];
        foreach ($flat as $key => $def) {
            $value = trim((string)($values[$key] ?? $def['default']));
            if ($value === '') {
                continue;
            }
            $lines[] = sprintf('$%s: %s;', $key, $this->normalize($def['type'], $value));
        }
        return implode("\n", $lines) . "\n";
    }

    private function normalize(string $type, string $value): string
    {
        // Quote font stacks if they contain spaces/commas and are not already quoted.
        if ($type === BootstrapVariableRegistry::TYPE_FONT) {
            return $value;
        }
        return $value;
    }

    /**
     * Composes the pre-bootstrap variable layer.
     *
     * A Bootswatch _variables.scss is self-contained: it declares its own palette
     * ($yellow, $gray-700, …) BEFORE referencing them ($warning: $yellow !default;),
     * so it compiles correctly on its own ahead of the Bootstrap import. We therefore
     * emit it VERBATIM and in full – never line-filter it, or internal references break.
     *
     * Order:
     *   1. Full preset _variables.scss (with its !default declarations)
     *   2. User overrides WITHOUT !default -> they override the preset defaults and win.
     *
     * Because Bootstrap's own _variables.scss is imported afterwards with !default,
     * both the preset and user values take precedence over Bootstrap's defaults.
     */
    public function composeVariableLayer(string $userVariablesScss, string $presetVariablesScss): string
    {
        $parts = [];
        $preset = rtrim($presetVariablesScss);
        if ($preset !== '') {
            $parts[] = "// --- Bootswatch preset variables (verbatim) ---";
            $parts[] = $preset;
        }
        $user = trim($this->stripDefaultFlags($userVariablesScss));
        if ($user !== '') {
            $parts[] = "// --- User overrides (no !default, so they win) ---";
            $parts[] = $user;
        }
        return implode("\n\n", $parts) . "\n";
    }

    /**
     * Removes any "!default" flags so user overrides always beat preset/Bootstrap defaults.
     */
    private function stripDefaultFlags(string $scss): string
    {
        return preg_replace('/\s*!default\s*;/', ';', $scss) ?? $scss;
    }
}
